name: triple
description: Segmented State Pattern
version: 0.0.1
homepage: https://github.com/Flutterando/triple_pattern

environment:
  sdk: '>=2.12.0-0 <3.0.0'


dev_dependencies:
  test: ^1.16.0-nullsafety.13
  meta: ^1.3.0-nullsafety.6
