name: mobx_triple
description: Segmented State Pattern for MobX
version: 1.0.0
homepage: https://github.com/Flutterando/triple_pattern

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  mobx: 2.0.0-nullsafety.2
  meta: ^1.3.0
  triple: ">=1.0.0 <2.0.0"

dev_dependencies:
  test: ^1.16.5



# dependency_overrides:
#   triple: 
#     path: ../triple

